import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          variables: {
            colorText: "#fff",
            colorBackground: "#1C1F2E",
            colorPrimary: "#0E78F9",
            colorInputBackground: "#252A41",
            colorInputText: "#fff",
            colorTextOnPrimaryBackground: "#fff",
          },
        }}>
        <body className={cn(inter.className, "bg-dark-1 text-white")}>
          {children}
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
